// src/components/Button.svelte
<script lang="ts">
  export let to: string;
</script>

<a
  href={to}
  as="button"
  role="button"
  class="flex justify-end rounded border-2 border-fuchsia-700 py-1 px-3 text-lg font-bold text-fuchsia-700 hover:bg-gray-100 dark:border-fuchsia-400 dark:text-fuchsia-400 dark:hover:bg-stone-800"
>
  <slot />
</a>

// src/components/Button.tsx
import type { ReactNode } from "react";

interface Props {
  to: string;
  children: ReactNode;
}

export default function Button({ to, children }: Props) {
  return (
    <a
      href={to}
      role="button"
      className="flex justify-end rounded py-1 px-3 text-lg font-bold text-fuchsia-700 underline hover:bg-gray-100 dark:border-fuchsia-400 dark:text-fuchsia-400 dark:hover:bg-stone-800"
    >
      {children}
    </a>
  );
}
