// app/components/Button.tsx
import { ButtonHTMLAttributes, ReactNode } from "react";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  children: ReactNode;
  handleClick?: (
    event: React.MouseEvent<HTMLButtonElement, MouseEvent>
  ) => void;
}

export function Button({ children, handleClick, ...rest }: ButtonProps) {
  return (
    <button
      {...rest}
      className="rounded border-2 border-stone-900 px-3 py-1.5 lowercase hover:bg-gray-100 dark:border-white dark:hover:bg-gray-800"
    >
      {children}
    </button>
  );
}

// src/components/Button.svelte
<script lang="ts">
  export let to: string;
</script>

<a
  href={to}
  type="button"
  class="flex justify-end rounded border-2 border-fuchsia-700 py-1 px-3 text-lg font-bold text-fuchsia-700 hover:bg-gray-100 dark:border-fuchsia-400 dark:text-fuchsia-400 dark:hover:bg-stone-800"
>
  <slot />
</a>
