// src/components/NerdAlert.svelte
<div class="stripes mt-10 flex w-full justify-center py-10">
  <div
    class="flex max-w-md items-center justify-center border-8 border-black bg-white p-3 "
  >
    <div class="px-2 text-3xl font-medium text-black">NERD ALERT</div>
  </div>
</div>

<style>
  .stripes {
    background-image: repeating-linear-gradient(
      120deg,
      theme("colors.yellow.400") 0,
      theme("colors.yellow.400") 30px,
      theme("colors.gray.700") 30px,
      theme("colors.gray.700") 60px
    );
  }
</style>

// src/components/NerdAlert.tsx
const stripeStyle: React.CSSProperties = {
  backgroundImage:
    "repeating-linear-gradient(120deg, #facc15 0, #facc15 30px, #374151 30px, #374151 60px)",
};

export default function NerdAlert() {
  return (
    <div
      data-testid="nerd-alert"
      className="mt-10 flex w-full justify-center py-10"
      style={stripeStyle}
    >
      <div className="flex max-w-md items-center justify-center border-8 border-black bg-white p-3">
        <div className="px-2 text-3xl font-medium text-black">NERD ALERT</div>
      </div>
    </div>
  );
}
