// src/lib/components/SpoilerAlert.svelte
<div class="stripes mt-10 flex w-full justify-center py-10">
  <div
    class="flex max-w-md items-center justify-center border-8 border-black bg-white p-3 "
  >
    <div class="px-2 text-3xl font-medium text-black">SPOILER ALERT</div>
  </div>
</div>

<style>
  .stripes {
    background-image: repeating-linear-gradient(
      120deg,
      theme("colors.orange.500") 0,
      theme("colors.orange.500") 30px,
      theme("colors.gray.700") 30px,
      theme("colors.gray.700") 60px
    );
  }
</style>

// src/components/SpoilerAlert.tsx
const stripeStyle: React.CSSProperties = {
  backgroundImage:
    "repeating-linear-gradient(120deg, #f97316 0, #f97316 30px, #374151 30px, #374151 60px)",
};

export default function SpoilerAlert() {
  return (
    <div
      data-testid="spoiler-alert"
      className="mt-10 flex w-full justify-center py-10"
      style={stripeStyle}
    >
      <div className="flex max-w-md items-center justify-center border-8 border-black bg-white p-3">
        <div className="px-2 text-3xl font-medium text-black">
          SPOILER ALERT
        </div>
      </div>
    </div>
  );
}
