// src/components/Tooltip.tsx
import { useState, useRef, useEffect, type ReactNode } from "react";
import Link from "./Link";

interface Props {
  main: ReactNode;
  hover: ReactNode;
  to?: string;
}

export default function Tooltip({ main, hover, to }: Props) {
  const [isOpen, setIsOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const rootRef = useRef<HTMLSpanElement>(null);
  const timeoutRef = useRef<ReturnType<typeof setTimeout>>(null);

  useEffect(() => {
    setIsMobile(
      /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        navigator.userAgent,
      ),
    );
  }, []);

  useEffect(() => {
    if (!isMobile || !isOpen) return;

    const handleTouchOutside = (e: TouchEvent) => {
      if (rootRef.current && !rootRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };

    document.addEventListener("touchstart", handleTouchOutside, {
      capture: true,
      passive: true,
    });
    return () =>
      document.removeEventListener("touchstart", handleTouchOutside, {
        capture: true,
      });
  }, [isMobile, isOpen]);

  const show = () => {
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    setIsOpen(true);
  };

  const hide = () => {
    timeoutRef.current = setTimeout(() => setIsOpen(false), 100);
  };

  const triggerContent =
    isMobile && to ? (
      <span className="font-medium text-orange-600 dark:text-orange-400">
        {main}
      </span>
    ) : to ? (
      <Link className="no-underline" style={{ textWrap: "nowrap" }} to={to}>
        {main}
      </Link>
    ) : (
      main
    );

  const popupContent =
    isMobile && to ? (
      <a
        rel="noreferrer"
        className="text-white underline"
        href={to}
        target="_blank"
      >
        {hover}
      </a>
    ) : (
      hover
    );

  return (
    <span ref={rootRef} className="relative !my-0 inline-flex">
      <span
        className="border-b-2 border-dotted border-fuchsia-700"
        onMouseEnter={show}
        onMouseLeave={hide}
        onTouchStart={show}
      >
        {triggerContent}
      </span>
      {isOpen && (
        <span
          role="tooltip"
          className="absolute bottom-full left-1/2 z-50 mb-1 w-max max-w-[250px] -translate-x-1/2 rounded bg-fuchsia-700 p-2 text-center text-sm leading-5 text-white"
          onMouseEnter={show}
          onMouseLeave={hide}
        >
          {popupContent}
        </span>
      )}
    </span>
  );
}

// src/components/Tooltip.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { browser } from "$app/env";
  import Link from "./Link.svelte";

  export let to: string = "";

  let open: boolean = false;
  let openFunc = () => (open = true);
  let el: HTMLElement;
  let elMain: HTMLElement;
  let classXTranslate: string = "-translate-x-1/2";
  let offset = 0;
  let isMobile = false;

  if (browser) {
    isMobile =
      /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        navigator.userAgent
      );

    onMount(() => {
      const updateXPosition = () => {
        if (!el || !elMain) return;
        const { right, left } = el.getBoundingClientRect();
        const { width } = elMain.getBoundingClientRect();
        const windowWidth = window.document.body.clientWidth;

        if (right > windowWidth - 12) {
          offset = right - windowWidth + 132 + 12;
          classXTranslate = "";
        } else if (left < 12) {
          offset = Math.ceil(width) / 2;
          classXTranslate = "";
        } else classXTranslate = "-translate-x-1/2";
      };
      updateXPosition();
      window.addEventListener("resize", updateXPosition);

      window.document.addEventListener(
        "touchstart",
        (event: TouchEvent) => {
          if (el.contains(event.target as Node)) return;
          open && (open = false);
        },
        { capture: true, passive: true }
      );
    });
  }
</script>

<span class="relative !my-0 inline-flex">
  <span
    class="border-b-2 border-dotted border-fuchsia-700"
    bind:this={elMain}
    on:touchstart={openFunc}
    on:mouseenter={openFunc}
    on:mouseleave={() => (open = false)}
  >
    {#if to && !isMobile}
      <Link class="no-underline" {to}>
        <slot name="main" />
      </Link>
    {:else if to}
      <span class="font-medium text-orange-600 dark:text-orange-400">
        <slot name="main" />
      </span>
    {:else}
      <slot name="main" />
    {/if}
  </span>
  <span
    bind:this={el}
    class:visible={open}
    class:invisible={!open}
    class={`absolute left-1/2 -mr-[270px] max-w-[250px] -translate-y-full rounded bg-fuchsia-700 p-2 text-center text-sm leading-5 text-white ${classXTranslate}`}
    style={`${offset !== 0 ? `transform: translate(-${offset}px, -100%)` : ""}`}
    on:blur={() => (open = false)}
  >
    {#if to && isMobile}
      <a class="text-white underline" href={to} target="_blank">
        <slot name="hover" />
      </a>
    {:else}
      <slot name="hover" />
    {/if}
  </span>
</span>
